# Generated by Django 4.0.4 on 2022-06-10 12:44

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_alter_article_access_alter_article_topic_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_author',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('subscriber', 'Подписчик'), ('author', 'Автор')], default='subscriber', max_length=32, verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='article',
            name='access',
            field=models.CharField(choices=[('public', 'Публичная статья'), ('for_subscribers', 'Только для подписчиков')], max_length=32, verbose_name='Доступность статьи'),
        ),
    ]
