# Generated by Django 4.0.4 on 2022-06-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0004_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='access',
        ),
        migrations.AddField(
            model_name='article',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Приватная статья'),
        ),
    ]
